// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioRecorderController from "./audio_recorder_controller"
application.register("audio-recorder", AudioRecorderController)

import AudioUploaderController from "./audio_uploader_controller"
application.register("audio-uploader", AudioUploaderController)

import ConnectController from "./connect_controller"
application.register("connect", ConnectController)

import ContactPickerController from "./contact_picker_controller"
application.register("contact-picker", ContactPickerController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import LoadableController from "./loadable_controller"
application.register("loadable", LoadableController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import OnboardingConnectController from "./onboarding_connect_controller"
application.register("onboarding-connect", OnboardingConnectController)

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
