// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationStatusController from "./notification_status_controller"
application.register("notification-status", NotificationStatusController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import PhoneInputController from "./phone_input_controller"
application.register("phone-input", PhoneInputController)

import ChipAuthController from "./chip_auth_controller"
application.register("chip-auth", ChipAuthController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import AddClientController from "./add_client_controller"
application.register("add-client", AddClientController)

import ClientFilterController from "./client_filter_controller"
application.register("client-filter", ClientFilterController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TableFilterController from "./table_filter_controller"
application.register("table-filter", TableFilterController)

import AmountInputController from "./amount_input_controller"
application.register("amount-input", AmountInputController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import DashboardChartController from "./dashboard_chart_controller"
application.register("dashboard-chart", DashboardChartController)
