import { Controller } from "@hotwired/stimulus"

// Attach to a <button> or to the <form> generated by button_to.
// On submit/click, swaps content for spinner + optional loading text,
// sets aria-busy, disables the button, and restores on turbo:submit-end.
//
// Values:
//   loading-text  — text shown next to spinner (omit to keep original label)
//   spinner-only  — true: render only the spinner (icon-only buttons)
export default class extends Controller {
  static values = {
    loadingText: String,
    spinnerOnly: { type: Boolean, default: false },
  }

  connect() {
    this._button   = this.element.tagName === "BUTTON"
      ? this.element
      : this.element.querySelector("button[type=submit], button:not([type])")

    if (!this._button) return

    this._original = this._button.innerHTML

    if (this.element.tagName === "FORM" || this.element.closest("form") !== this.element) {
      // button_to pattern: data-controller is on the <form>
      this.element.addEventListener("submit",          this._onSubmit)
      this.element.addEventListener("turbo:submit-end", this._onEnd)
    } else {
      // standalone button
      this._button.addEventListener("click", this._onSubmit)
      this._button.closest("form")?.addEventListener("turbo:submit-end", this._onEnd)
    }
  }

  disconnect() {
    this.element.removeEventListener("submit",           this._onSubmit)
    this.element.removeEventListener("turbo:submit-end", this._onEnd)
    this._button?.removeEventListener("click", this._onSubmit)
    this._button?.closest("form")?.removeEventListener("turbo:submit-end", this._onEnd)
  }

  _onSubmit = () => {
    if (!this._button) return
    this._button.disabled = true
    this._button.setAttribute("aria-busy", "true")

    if (this.spinnerOnlyValue) {
      this._button.innerHTML = '<span class="btn-spinner"></span>'
    } else {
      const text = this.loadingTextValue || this._button.textContent.trim()
      this._button.innerHTML = `<span class="btn-spinner"></span><span>${text}</span>`
    }
  }

  _onEnd = () => {
    if (!this._button) return
    this._button.disabled = false
    this._button.removeAttribute("aria-busy")
    this._button.innerHTML = this._original
  }
}
